CREATE TABLE [dbo].[Vehicles]
(
    VehicleId  INT IDENTITY (1, 1),
    ManufacturerName NVARCHAR(MAX) NOT NULL,
    Model  NVARCHAR(MAX) NOT NULL,
    
    CONSTRAINT PK_dbo_Vehicles_VehicleId
        PRIMARY KEY  (VehicleId)
);

INSERT INTO [dbo].[Vehicles] (ManufacturerName, Model)
VALUES  (N'MAZDA', N'BT 50 SERIES'),
        (N'VOLVO', N'V90'),
        (N'MAZDA', N'6'),
        (N'ALFA ROMEO', N'GIULIETTA'),
        (N'ALFA ROMEO', N'MiTO'),
        (N'ALFA ROMEO', N'GIULIA'),
        (N'ALFA ROMEO', N'TONALE'),
        (N'ALFA ROMEO', N'4C'),
        (N'VOLVO', N'XC70'),
        (N'VOLVO', N'XC60'),
        (N'RENAULT', N'KANGOO'),
        (N'RENAULT', N'KWID'),
        (N'RENAULT', N'MIDLUM'),
        (N'RENAULT', N'TRIBER'),
        (N'RENAULT', N'TRAFIC'),
        (N'RENAULT', N'SANDERO'),
        (N'JAGUAR', N'XE'),
        (N'RENAULT', N'PREMIUM'),
        (N'ALFA ROMEO', N'STELVIO'),
        (N'MAZDA', N'CX-5'),
        (N'JAGUAR', N'XF'),
        (N'MAZDA', N'MX5'),
        (N'JAGUAR', N'E-PACE'),
        (N'JAGUAR', N'F-PACE'),
        (N'VOLVO', N'S90'),
        (N'VOLVO', N'FH'),
        (N'VOLVO', N'XC90'),
        (N'LAND ROVER', N'FREELANDER'),
        (N'LAND ROVER', N'DEFENDER 90'),
        (N'LAND ROVER', N'DISCOVERY SPORT'),
        (N'LAND ROVER', N'DISCOVERY'),
        (N'LAND ROVER', N'DEFENDER'),
        (N'LAND ROVER', N'DEFENDER 110'),
        (N'AUDI', N'A1'),
        (N'LAND ROVER', N'DEFENDER 130'),
        (N'AUDI', N'A3'),
        (N'LAND ROVER', N'EVOQUE'),
        (N'JAGUAR', N'XJ'),
        (N'LAND ROVER', N'VELAR'),
        (N'JAGUAR', N'I-PACE'),
        (N'JAGUAR', N'F-TYPE'),
        (N'RENAULT', N'DUSTER'),
        (N'AUDI', N'S3'),
        (N'AUDI', N'RS3'),
        (N'HAVAL', N'H1'),
        (N'HAVAL', N'H2'),
        (N'HAVAL', N'H6'),
        (N'HAVAL', N'H9'),
        (N'HONDA', N'CRF'),
        (N'AUDI', N'A3 SPORTBACK'),
        (N'HONDA', N'BRIO'),
        (N'AUDI', N'Q2'),
        (N'AUDI', N'Q3'),
        (N'AUDI', N'A4'),
        (N'AUDI', N'A4 ALLROAD'),
        (N'AUDI', N'S4'),
        (N'AUDI', N'RS4'),
        (N'AUDI', N'e-TRON'),
        (N'AUDI', N'Q5'),
        (N'LAND ROVER', N'RANGE ROVER'),
        (N'LAND ROVER', N'RANGE ROVER SPORT'),
        (N'RENAULT', N'KIGER'),
        (N'RENAULT', N'CLIO IV'),
        (N'RENAULT', N'CAPTUR'),
        (N'HONDA', N'FIT'),
        (N'HONDA', N'JAZZ'),
        (N'HONDA', N'CIVIC'),
        (N'NISSAN', N'MICRA'),
        (N'NISSAN', N'MAGNITE'),
        (N'NISSAN', N'JUKE'),
        (N'NISSAN', N'NP200'),
        (N'NISSAN', N'LIVINA'),
        (N'AUDI', N'A5'),
        (N'AUDI', N'RS5'),
        (N'AUDI', N'A6'),
        (N'AUDI', N'A7'),
        (N'AUDI', N'RS7'),
        (N'AUDI', N'TT'),
        (N'FIAT', N'PANDA'),
        (N'FIAT', N'PUNTO'),
        (N'FIAT', N'FULLBACK'),
        (N'FIAT', N'500'),
        (N'FIAT', N'500X'),
        (N'FIAT', N'TIPO'),
        (N'FIAT', N'DOBLO'),
        (N'RENAULT', N'FLUENCE'),
        (N'RENAULT', N'MEGANE III'),
        (N'RENAULT', N'MEGANE IV'),
        (N'RENAULT', N'MEGANE'),
        (N'RENAULT', N'KADJAR'),
        (N'RENAULT', N'KOLEOS'),
        (N'JAGUAR', N'XK'),
        (N'JAGUAR', N'XKR'),
        (N'JEEP', N'RENEGADE'),
        (N'JEEP', N'PATRIOT'),
        (N'JEEP', N'WRANGLER'),
        (N'JEEP', N'GLADIATOR'),
        (N'JEEP', N'COMPASS'),
        (N'JEEP', N'CHEROKEE'),
        (N'JEEP', N'GRAND CHEROKEE'),
        (N'JEEP', N'SRT8'),
        (N'HONDA', N'WR-V'),
        (N'HONDA', N'PCX'),
        (N'HONDA', N'ACE'),
        (N'HONDA', N'XRL'),
        (N'HONDA', N'CB'),
        (N'HONDA', N'CBR'),
        (N'HONDA', N'CHA'),
        (N'HONDA', N'MSX'),
        (N'HONDA', N'XR'),
        (N'HONDA', N'TRX'),
        (N'HONDA', N'BALLADE'),
        (N'HONDA', N'CR-Z'),
        (N'NISSAN', N'ALMERA'),
        (N'NISSAN', N'HARDBODY'),
        (N'NISSAN', N'SENTRA 2013'),
        (N'NISSAN', N'LEAF'),
        (N'NISSAN', N'NAVARA'),
        (N'NISSAN', N'PRIMASTAR/ NV 200'),
        (N'NISSAN', N'PRIMASTAR/NV 200'),
        (N'NISSAN', N'NV200'),
        (N'VOLKSWAGEN', N'UP'),
        (N'VOLKSWAGEN', N'POLO VIVO GP'),
        (N'VOLKSWAGEN', N'POLO VIVO'),
        (N'VOLKSWAGEN', N'POLO GP'),
        (N'VOLKSWAGEN', N'POLO'),
        (N'VOLKSWAGEN', N'POLO CLASSIC'),
        (N'VOLKSWAGEN', N'T-CROSS'),
        (N'VOLKSWAGEN', N'TAIGO'),
        (N'HONDA', N'ACCORD'),
        (N'HONDA', N'HR-V'),
        (N'HONDA', N'MOBILIO'),
        (N'HONDA', N'BR-V'),
        (N'HONDA', N'NC'),
        (N'HONDA', N'CRV'),
        (N'HONDA', N'VFR'),
        (N'HONDA', N'CBF'),
        (N'HONDA', N'VFR 1200'),
        (N'HONDA', N'VTX'),
        (N'HONDA', N'GL'),
        (N'NISSAN', N'NV350'),
        (N'FIAT', N'FIORINO'),
        (N'AUDI', N'A8'),
        (N'AUDI', N'Q7'),
        (N'AUDI', N'Q8'),
        (N'AUDI', N'R8'),
        (N'NISSAN', N'NV'),
        (N'NISSAN', N'PATROL'),
        (N'NISSAN', N'QASHQAI'),
        (N'VOLKSWAGEN', N'CADDY'),
        (N'HYUNDAI', N'ATOS'),
        (N'HYUNDAI', N'i10'),
        (N'HYUNDAI', N'i20'),
        (N'VOLKSWAGEN', N'GOLF VII'),
        (N'VOLKSWAGEN', N'GOLF 7'),
        (N'VOLKSWAGEN', N'GOLF SV'),
        (N'HYUNDAI', N'i30'),
        (N'HYUNDAI', N'I30N'),
        (N'VOLKSWAGEN', N'GOLF VI'),
        (N'HYUNDAI', N'ACCENT'),
        (N'VOLKSWAGEN', N'GOLF 8'),
        (N'VOLKSWAGEN', N'GOLF 6'),
        (N'HYUNDAI', N'VENUE'),
        (N'VOLKSWAGEN', N'SCIROCCO'),
        (N'HYUNDAI', N'H100 / BAKKIE'),
        (N'FIAT', N'DUCATO'),
        (N'HYUNDAI', N'KONA'),
        (N'HYUNDAI', N'HD 72'),
        (N'FIAT', N'QUBO'),
        (N'VOLKSWAGEN', N'JETTA'),
        (N'VOLKSWAGEN', N'JETTA VI'),
        (N'VOLKSWAGEN', N'BEETLE'),
        (N'FORD', N'FIGO'),
        (N'HYUNDAI', N'EX-8'),
        (N'HYUNDAI', N'H-1'),
        (N'HYUNDAI', N'STARIA'),
        (N'HYUNDAI', N'H1'),
        (N'HYUNDAI', N'ELANTRA'),
        (N'HYUNDAI', N'CRETA'),
        (N'HYUNDAI', N'GRAND CRETA'),
        (N'HYUNDAI', N'TUCSON'),
        (N'HYUNDAI', N'iX35'),
        (N'HYUNDAI', N'VELOSTER'),
        (N'HYUNDAI', N'SANTA-FE'),
        (N'HYUNDAI', N'PALISADE'),
        (N'NISSAN', N'MURANO'),
        (N'NISSAN', N'370 Z'),
        (N'NISSAN', N'350 Z/370 Z'),
        (N'NISSAN', N'X TRAIL'),
        (N'NISSAN', N'PATHFINDER'),
        (N'VOLKSWAGEN', N'TOURAN'),
        (N'ISUZU', N'KB'),
        (N'VOLKSWAGEN', N'PASSAT'),
        (N'VOLKSWAGEN', N'AMAROK'),
        (N'ISUZU', N'D-MAX'),
        (N'FORD', N'RANGER'),
        (N'NISSAN', N'TERRA'),
        (N'NISSAN', N'GT-R'),
        (N'FORD', N'TRANSIT'),
        (N'ISUZU', N'NPR 275'),
        (N'ISUZU', N'N SERIES'),
        (N'ISUZU', N'NPR 300'),
        (N'ISUZU', N'NPS 300'),
        (N'ISUZU', N'NPR 400'),
        (N'FORD', N'FIESTA'),
        (N'ISUZU', N'NQR 500'),
        (N'ISUZU', N'NLR'),
        (N'ISUZU', N'NLR 150'),
        (N'ISUZU', N'NMR'),
        (N'ISUZU', N'NMR 250'),
        (N'FORD', N'IKON'),
        (N'FORD', N'ECOSPORT'),
        (N'ISUZU', N'FRR 550'),
        (N'SUBARU', N'XV'),
        (N'ISUZU', N'FRR'),
        (N'ISUZU', N'FRR 600'),
        (N'ISUZU', N'FSR'),
        (N'ISUZU', N'FSR 750'),
        (N'ISUZU', N'FTS'),
        (N'ISUZU', N'FTS 750'),
        (N'ISUZU', N'FSR 800'),
        (N'ISUZU', N'FTR'),
        (N'ISUZU', N'FTR 850'),
        (N'SUBARU', N'IMPREZA'),
        (N'ISUZU', N'FVR'),
        (N'ISUZU', N'FVR 900'),
        (N'ISUZU', N'FVM'),
        (N'ISUZU', N'FVM 1200'),
        (N'ISUZU', N'FVZ'),
        (N'ISUZU', N'FVZ 1400'),
        (N'ISUZU', N'FXR'),
        (N'ISUZU', N'FXZ'),
        (N'SUBARU', N'LEGACY'),
        (N'ISUZU', N'FYH'),
        (N'ISUZU', N'GRR'),
        (N'ISUZU', N'GSR'),
        (N'ISUZU', N'GXR'),
        (N'SUBARU', N'FORESTER'),
        (N'SUBARU', N'OUTBACK'),
        (N'ISUZU', N'GXZ'),
        (N'ISUZU', N'MU-X'),
        (N'VOLKSWAGEN', N'CC'),
        (N'VOLKSWAGEN', N'ARTEON'),
        (N'VOLKSWAGEN', N'T-ROC'),
        (N'VOLKSWAGEN', N'TIGUAN'),
        (N'VOLKSWAGEN', N'TRANSPORTER'),
        (N'OPEL', N'COMBO'),
        (N'OPEL', N'ADAM'),
        (N'OPEL', N'CORSA'),
        (N'OPEL', N'MERIVA'),
        (N'FORD', N'B-MAX'),
        (N'OPEL', N'ZAFIRA'),
        (N'MITSUBISHI', N'TRITON'),
        (N'OPEL', N'CROSSLAND X'),
        (N'MITSUBISHI', N'MIRAGE'),
        (N'MITSUBISHI', N'XPANDER'),
        (N'OPEL', N'CROSSLAND'),
        (N'OPEL', N'ASTRA'),
        (N'MITSUBISHI', N'ASX'),
        (N'MITSUBISHI', N'ECLIPSE CROSS'),
        (N'MITSUBISHI', N''),
        (N'MITSUBISHI', N'OUTLANDER'),
        (N'MITSUBISHI', N'PAJERO'),
        (N'MITSUBISHI', N'PAJERO SPORT'),
        (N'VOLKSWAGEN', N'CRAFTER'),
        (N'FORD', N'FOCUS'),
        (N'KIA', N'PICANTO'),
        (N'KIA', N'PEGAS'),
        (N'KIA', N'RIO'),
        (N'KIA', N'SOUL'),
        (N'KIA', N'K 2500'),
        (N'KIA', N'CERATO'),
        (N'OPEL', N'MOKKA'),
        (N'OPEL', N'GRANDLAND X'),
        (N'VOLKSWAGEN', N'CONSTELLATION'),
        (N'OPEL', N'VIVARO'),
        (N'VOLKSWAGEN', N'T6'),
        (N'VOLKSWAGEN', N'T5'),
        (N'VOLKSWAGEN', N'TOUAREG'),
        (N'VOLKSWAGEN', N'VOLKSBUS'),
        (N'FORD', N'FUSION'),
        (N'FORD', N'MUSTANG'),
        (N'FORD', N'KUGA'),
        (N'PEUGEOT', N'PARTNER'),
        (N'PEUGEOT', N'BOXER'),
        (N'FORD', N'TOURNEO CONNECT'),
        (N'PEUGEOT', N'107'),
        (N'PEUGEOT', N'107 / 108'),
        (N'FORD', N'EVEREST'),
        (N'KIA', N'K 2700'),
        (N'KIA', N'SONET'),
        (N'VOLVO', N'V40'),
        (N'KIA', N'CARENS'),
        (N'KIA', N'OPTIMA'),
        (N'KIA', N'SELTOS'),
        (N'FORD', N'TOURNEO'),
        (N'VOLVO', N'XC40'),
        (N'KIA', N'SPORTAGE'),
        (N'KIA', N'CARNIVAL'),
        (N'KIA', N'SEDONA'),
        (N'PEUGEOT', N'207'),
        (N'PEUGEOT', N'208'),
        (N'KIA', N'SORENTO'),
        (N'PEUGEOT', N'2008'),
        (N'KIA', N'STINGER'),
        (N'PEUGEOT', N'308'),
        (N'CITROEN', N'C1'),
        (N'CITROEN', N'ENTERPRISE'),
        (N'CITROEN', N'BERLINGO'),
        (N'VOLVO', N'S60'),
        (N'PEUGEOT', N'3008'),
        (N'PEUGEOT', N'RCZ'),
        (N'PEUGEOT', N'4008'),
        (N'PEUGEOT', N'5008'),
        (N'VOLVO', N'FM'),
        (N'VOLVO', N'FMX'),
        (N'MAZDA', N'MAZDA 2'),
        (N'VOLVO', N'V60'),
        (N'MAZDA', N'3'),
        (N'PEUGEOT', N'LANDTREK'),
        (N'PEUGEOT', N'508'),
        (N'MAZDA', N'CX-3'),
        (N'MAZDA', N'CX-30'),
        (N'MAZDA', N'5'),
        (N'CITROEN', N'C3'),
        (N'CITROEN', N'C4'),
        (N'GWM', N'M4'),
        (N'GWM', N'STEED 5'),
        (N'GWM', N'STEED'),
        (N'GWM', N'C30'),
        (N'GWM', N'C50'),
        (N'GWM', N'H5'),
        (N'GWM', N'H6'),
        (N'CITROEN', N'DISPATCH'),
        (N'CITROEN', N'C4 PICASSO'),
        (N'CITROEN', N'RELAY'),
        (N'CITROEN', N'C5'),
        (N'GWM', N'P-SERIES'),
        (N'HAVAL', N'JOLION'),
        (N'HONDA', N'750'),
        (N'ISUZU', N'NPR'),
        (N'ISUZU', N'NQR'),
        (N'MAZDA', N'CX-60'),
        (N'SUBARU', N'CROSSTREK'),
        (N'VOLVO', N'C40'),
        (N'OPEL', N'GRANDLAND');